name: Copy of Person classifier on camera
description: This example showcases person classification on camera, using a camera stream from USB camera
ports: []
bricks:
- arduino:video_image_classification: {
    variables: {
      EI_CLASSIFICATION_MODEL: /home/arduino/.arduino-bricks/ei-models/drowsiness-detector-linux-aarch64-v2.eim
    }
  }
- arduino:web_ui: {}
icon: 🚶‍♂️
